// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaHWq2GfNbAjqtDVowKtkTCslI3ngIM2k',
    appId: '1:40756926746:web:6d004134ed3b33e143b4a3',
    messagingSenderId: '40756926746',
    projectId: 'sv-teste',
    authDomain: 'sv-teste.firebaseapp.com',
    storageBucket: 'sv-teste.appspot.com',
    measurementId: 'G-KHRCTVLYHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBRUWJwtoVK-zYqotms9Ky_ZAKcInu_bc',
    appId: '1:40756926746:android:39fd6bf2ba247aae43b4a3',
    messagingSenderId: '40756926746',
    projectId: 'sv-teste',
    storageBucket: 'sv-teste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKazS48xMFKzR96UI-qONCep4pcmejC4I',
    appId: '1:40756926746:ios:267195718be3a74c43b4a3',
    messagingSenderId: '40756926746',
    projectId: 'sv-teste',
    storageBucket: 'sv-teste.appspot.com',
    iosClientId: '40756926746-o23no80usmohui63b5up0ku7v7t6r3j6.apps.googleusercontent.com',
    iosBundleId: 'br.com.gustavo.flutterApplicationSvTeste',
  );
}
